// ---------------------------------------------------------------------------
// Mock data for the Agentic Bus dashboard
// ---------------------------------------------------------------------------

import {
  AuditLogEntry,
  DashboardStats,
  EphemeralAgent,
  ManagedAgent,
  PersistentAgent,
  SessionInfo,
} from "./types";

// ── Persistent Agents ─────────────────────────────────────────────────────

export const mockPersistentAgents: PersistentAgent[] = [
  {
    agent_id: "agent-analytics-v2",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "approved",
    semantic_description:
      "Advanced data analytics agent capable of running SQL queries, building dashboards, and performing statistical analysis.",
    version: "2.1.0",
    capabilities: [
      {
        capability_id: "sql-query",
        description: "Execute SQL queries against configured data sources",
        estimated_cost: 0.01,
        estimated_latency: 2.5,
      },
      {
        capability_id: "chart-generation",
        description: "Generate interactive charts and visualisations",
        estimated_cost: 0.02,
        estimated_latency: 5.0,
      },
    ],
    required_scopes: ["data:read", "data:analytics"],
    supported_domains: ["finance", "marketing"],
    enrolled_at: "2026-02-15T10:30:00Z",
    approved_at: "2026-02-15T11:00:00Z",
    approved_by: "admin@corp.example",
    last_connected_at: "2026-02-20T08:45:00Z",
    total_executions: 47,
    current_score: 8.3,
    mean_latency_ms: 3200,
    last_execution_at: "2026-02-20T08:40:00Z",
  },
  {
    agent_id: "agent-email-composer",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "approved",
    semantic_description:
      "Composes and sends email drafts using natural language instructions.",
    version: "1.3.0",
    capabilities: [
      {
        capability_id: "email-draft",
        description: "Compose email drafts from natural language prompts",
        estimated_cost: 0.005,
        estimated_latency: 3.0,
      },
    ],
    required_scopes: ["email:write"],
    supported_domains: ["communication"],
    enrolled_at: "2026-02-10T14:20:00Z",
    approved_at: "2026-02-10T14:30:00Z",
    approved_by: "admin@corp.example",
    last_connected_at: "2026-02-19T17:30:00Z",
    total_executions: 23,
    current_score: 7.1,
    mean_latency_ms: 2800,
    last_execution_at: "2026-02-19T17:20:00Z",
  },
  {
    agent_id: "agent-code-reviewer",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "pending",
    semantic_description:
      "Reviews pull requests and provides detailed code review feedback with security analysis.",
    version: "0.9.0",
    capabilities: [
      {
        capability_id: "code-review",
        description: "Analyse code changes and provide review feedback",
        estimated_cost: 0.05,
        estimated_latency: 15.0,
      },
      {
        capability_id: "security-scan",
        description: "Perform static security analysis on source code",
        estimated_cost: 0.03,
        estimated_latency: 10.0,
      },
    ],
    required_scopes: ["code:read", "code:review"],
    supported_domains: ["engineering"],
    enrolled_at: "2026-02-19T09:00:00Z",
    approved_at: null,
    approved_by: null,
    last_connected_at: null,
    total_executions: 0,
    current_score: 0,
    mean_latency_ms: 0,
    last_execution_at: null,
  },
  {
    agent_id: "agent-doc-search",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "approved",
    semantic_description:
      "Searches internal documentation and knowledge bases to answer questions.",
    version: "1.0.2",
    capabilities: [
      {
        capability_id: "doc-search",
        description: "Semantic search across internal documentation",
        estimated_cost: 0.008,
        estimated_latency: 1.5,
      },
    ],
    required_scopes: ["docs:read"],
    supported_domains: ["knowledge"],
    enrolled_at: "2026-01-28T16:00:00Z",
    approved_at: "2026-01-28T16:15:00Z",
    approved_by: "admin@corp.example",
    last_connected_at: "2026-02-20T09:10:00Z",
    total_executions: 112,
    current_score: 9.1,
    mean_latency_ms: 1400,
    last_execution_at: "2026-02-20T09:05:00Z",
  },
  {
    agent_id: "agent-slack-bot",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "revoked",
    semantic_description:
      "Slack integration agent for posting messages and managing channels.",
    version: "0.5.0",
    capabilities: [
      {
        capability_id: "slack-post",
        description: "Post messages to Slack channels",
        estimated_cost: 0.001,
        estimated_latency: 0.5,
      },
    ],
    required_scopes: ["slack:write"],
    supported_domains: ["communication"],
    enrolled_at: "2026-01-15T12:00:00Z",
    approved_at: "2026-01-15T12:30:00Z",
    approved_by: "admin@corp.example",
    last_connected_at: "2026-02-01T10:00:00Z",
    total_executions: 5,
    current_score: 4.2,
    mean_latency_ms: 500,
    last_execution_at: "2026-01-30T14:00:00Z",
  },
  {
    agent_id: "agent-calendar-sync",
    public_key_pem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA...",
    status: "rejected",
    semantic_description:
      "Synchronises calendar events across Google Calendar and Outlook.",
    version: "0.2.0",
    capabilities: [
      {
        capability_id: "calendar-sync",
        description: "Bi-directional calendar synchronisation",
        estimated_cost: 0.01,
        estimated_latency: 4.0,
      },
    ],
    required_scopes: ["calendar:read", "calendar:write"],
    supported_domains: ["productivity"],
    enrolled_at: "2026-02-18T08:00:00Z",
    approved_at: null,
    approved_by: null,
    last_connected_at: null,
    total_executions: 0,
    current_score: 0,
    mean_latency_ms: 0,
    last_execution_at: null,
  },
];

// ── Managed Agents ────────────────────────────────────────────────────────

export const mockManagedAgents: ManagedAgent[] = [
  {
    id: 1,
    agent_id: "managed-researcher",
    name: "Research Specialist",
    role: "Senior Research Analyst",
    goal: "Provide thorough, well-sourced research on any given topic",
    backstory:
      "You are a meticulous research analyst with 15 years of experience across multiple industries. You excel at finding, synthesising, and presenting information.",
    llm_config_name: null,
    verbose: false,
    max_iter: 25,
    max_rpm: null,
    memory: true,
    tools: ["SerperDevTool", "WebsiteSearchTool"],
    tool_config: {},
    status: "active",
    capabilities: [
      {
        id: 1,
        capability_id: "web-research",
        description: "Perform comprehensive web research on a given topic",
        expected_output: "A structured research report with citations",
        required_scopes: ["web:search"],
        supported_data_domains: ["general"],
        estimated_cost: 0.05,
        estimated_latency: 30.0,
        output_fields: [],
        output_schema: {},
      },
    ],
    total_executions: 34,
    current_score: 8.7,
    mean_latency_ms: 4500,
    last_execution_at: "2026-02-20T07:30:00Z",
    created_at: "2026-02-12T10:00:00Z",
    updated_at: "2026-02-18T14:30:00Z",
    created_by: "admin",
  },
  {
    id: 2,
    agent_id: "managed-writer",
    name: "Content Writer",
    role: "Senior Content Writer",
    goal: "Produce high-quality, engaging written content",
    backstory:
      "You are an award-winning content writer skilled at adapting tone and style to match any audience.",
    llm_config_name: null,
    verbose: true,
    max_iter: 15,
    max_rpm: 10,
    memory: true,
    tools: ["FileReadTool"],
    tool_config: {},
    status: "active",
    capabilities: [
      {
        id: 2,
        capability_id: "content-writing",
        description: "Write articles, blog posts, and marketing copy",
        expected_output: "Polished written content in Markdown format",
        required_scopes: [],
        supported_data_domains: ["marketing", "general"],
        estimated_cost: 0.03,
        estimated_latency: 20.0,
        output_fields: [],
        output_schema: {},
      },
    ],
    total_executions: 18,
    current_score: 7.5,
    mean_latency_ms: 6200,
    last_execution_at: "2026-02-19T16:10:00Z",
    created_at: "2026-02-14T09:00:00Z",
    updated_at: "2026-02-14T09:00:00Z",
    created_by: "admin",
  },
  {
    id: 3,
    agent_id: "managed-summariser",
    name: "Document Summariser",
    role: "Document Analysis Specialist",
    goal: "Create concise, accurate summaries of long documents",
    backstory:
      "You specialise in extracting key insights from lengthy documents while preserving critical details.",
    llm_config_name: null,
    verbose: false,
    max_iter: 10,
    max_rpm: null,
    memory: false,
    tools: ["FileReadTool"],
    tool_config: {},
    status: "draft",
    capabilities: [],
    total_executions: 0,
    current_score: 0,
    mean_latency_ms: 0,
    last_execution_at: null,
    created_at: "2026-02-19T16:00:00Z",
    updated_at: "2026-02-19T16:00:00Z",
    created_by: "admin",
  },
];

// ── Ephemeral Agents ──────────────────────────────────────────────────────

export const mockEphemeralAgents: EphemeralAgent[] = [
  {
    agent_id: "eph-logistics-tracker",
    version: "1.0.0",
    status: "online",
    semantic_description:
      "Real-time logistics tracking agent that monitors shipment status and provides ETAs.",
    capabilities: [
      {
        capability_id: "shipment-track",
        description: "Track shipment status in real-time using carrier APIs",
        estimated_cost: 0.002,
        estimated_latency: 1.0,
      },
      {
        capability_id: "eta-prediction",
        description: "Predict estimated time of arrival based on current logistics data",
        estimated_cost: 0.005,
        estimated_latency: 2.0,
      },
    ],
    required_scopes: ["logistics:read"],
    supported_domains: ["logistics", "supply-chain"],
    operational_constraints: { max_concurrent_requests: 50 },
    registered_at: "2026-02-20T09:00:00Z",
  },
  {
    agent_id: "eph-sentiment-analyser",
    version: "0.3.0",
    status: "online",
    semantic_description:
      "Analyses customer feedback and social media posts for sentiment classification.",
    capabilities: [
      {
        capability_id: "sentiment-classify",
        description: "Classify text sentiment as positive, negative, or neutral",
        estimated_cost: 0.001,
        estimated_latency: 0.5,
      },
    ],
    required_scopes: ["nlp:analyse"],
    supported_domains: ["marketing", "customer-success"],
    operational_constraints: {},
    registered_at: "2026-02-20T08:30:00Z",
  },
  {
    agent_id: "eph-pdf-extractor",
    version: "2.0.1",
    status: "online",
    semantic_description:
      "Extracts structured data from PDF documents including tables, forms, and invoices.",
    capabilities: [
      {
        capability_id: "pdf-extract",
        description: "Extract text and structured data from PDF files",
        estimated_cost: 0.01,
        estimated_latency: 5.0,
      },
      {
        capability_id: "invoice-parse",
        description: "Parse invoice PDFs into structured JSON records",
        estimated_cost: 0.015,
        estimated_latency: 8.0,
      },
    ],
    required_scopes: ["docs:read", "docs:extract"],
    supported_domains: ["finance", "legal"],
    operational_constraints: { max_file_size_mb: 50 },
    registered_at: "2026-02-20T07:45:00Z",
  },
];

// ── Sessions ──────────────────────────────────────────────────────────────

export const mockSessions: SessionInfo[] = [
  {
    session_id: "sess-a1b2c3d4",
    phase: "execution",
    requester_id: "user-jane",
    discovered_agents: ["agent-analytics-v2", "agent-doc-search"],
    accepted_offers: ["agent-analytics-v2"],
    created_at: "2026-02-20T09:15:00Z",
    dissolved_at: null,
  },
  {
    session_id: "sess-e5f6g7h8",
    phase: "completed",
    requester_id: "user-bob",
    discovered_agents: ["agent-email-composer"],
    accepted_offers: ["agent-email-composer"],
    created_at: "2026-02-20T08:30:00Z",
    dissolved_at: "2026-02-20T08:35:00Z",
  },
  {
    session_id: "sess-i9j0k1l2",
    phase: "dissolved",
    requester_id: "user-alice",
    discovered_agents: [
      "agent-analytics-v2",
      "agent-doc-search",
      "managed-researcher",
    ],
    accepted_offers: ["managed-researcher"],
    created_at: "2026-02-20T07:00:00Z",
    dissolved_at: "2026-02-20T07:20:00Z",
  },
];

// ── Audit Log ─────────────────────────────────────────────────────────────

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: "log-001",
    timestamp: "2026-02-20T09:15:00Z",
    action: "session.created",
    actor: "user-jane",
    target: "sess-a1b2c3d4",
    target_type: "session",
    details: 'Intent: "Analyse Q4 revenue trends and create a summary chart"',
    severity: "info",
  },
  {
    id: "log-002",
    timestamp: "2026-02-20T09:10:00Z",
    action: "agent.connected",
    actor: "agent-doc-search",
    target: "agent-doc-search",
    target_type: "agent",
    details: "Challenge–response authentication successful",
    severity: "info",
  },
  {
    id: "log-003",
    timestamp: "2026-02-20T09:00:00Z",
    action: "ibac.evaluation",
    actor: "coordinator",
    target: "sess-a1b2c3d4",
    target_type: "session",
    details:
      "IBAC evaluation passed for agent-analytics-v2 (scopes: data:read, data:analytics)",
    severity: "info",
  },
  {
    id: "log-004",
    timestamp: "2026-02-20T08:45:00Z",
    action: "agent.connected",
    actor: "agent-analytics-v2",
    target: "agent-analytics-v2",
    target_type: "agent",
    details: "Challenge–response authentication successful",
    severity: "info",
  },
  {
    id: "log-005",
    timestamp: "2026-02-20T08:35:00Z",
    action: "session.dissolved",
    actor: "coordinator",
    target: "sess-e5f6g7h8",
    target_type: "session",
    details: "Session completed and dissolved per Invariant II",
    severity: "info",
  },
  {
    id: "log-006",
    timestamp: "2026-02-20T08:30:00Z",
    action: "session.created",
    actor: "user-bob",
    target: "sess-e5f6g7h8",
    target_type: "session",
    details: 'Intent: "Draft a follow-up email to the design team"',
    severity: "info",
  },
  {
    id: "log-007",
    timestamp: "2026-02-20T07:20:00Z",
    action: "session.dissolved",
    actor: "coordinator",
    target: "sess-i9j0k1l2",
    target_type: "session",
    details: "Session completed and dissolved per Invariant II",
    severity: "info",
  },
  {
    id: "log-008",
    timestamp: "2026-02-19T17:30:00Z",
    action: "agent.disconnected",
    actor: "agent-email-composer",
    target: "agent-email-composer",
    target_type: "agent",
    details: "Clean WebSocket disconnect",
    severity: "info",
  },
  {
    id: "log-009",
    timestamp: "2026-02-19T09:00:00Z",
    action: "agent.enrolled",
    actor: "agent-code-reviewer",
    target: "agent-code-reviewer",
    target_type: "agent",
    details: "New agent enrolment – status: pending",
    severity: "warning",
  },
  {
    id: "log-010",
    timestamp: "2026-02-18T15:00:00Z",
    action: "ibac.denied",
    actor: "coordinator",
    target: "sess-x1y2z3",
    target_type: "session",
    details:
      "IBAC denied agent-slack-bot: missing scope slack:admin. Session aborted.",
    severity: "error",
  },
  {
    id: "log-011",
    timestamp: "2026-02-18T08:00:00Z",
    action: "agent.rejected",
    actor: "admin@corp.example",
    target: "agent-calendar-sync",
    target_type: "agent",
    details:
      "Rejected: insufficient security review for calendar write permissions",
    severity: "warning",
  },
  {
    id: "log-012",
    timestamp: "2026-02-17T14:00:00Z",
    action: "llm.config_activated",
    actor: "admin@corp.example",
    target: "gpt-4o-main",
    target_type: "llm_config",
    details: "Switched active LLM to gpt-4o-main (openai/gpt-4o)",
    severity: "info",
  },
  {
    id: "log-013",
    timestamp: "2026-02-15T11:00:00Z",
    action: "agent.approved",
    actor: "admin@corp.example",
    target: "agent-analytics-v2",
    target_type: "agent",
    details: "Agent approved after security review",
    severity: "info",
  },
  {
    id: "log-014",
    timestamp: "2026-02-14T10:00:00Z",
    action: "system.startup",
    actor: "coordinator",
    target: "coordinator",
    target_type: "system",
    details: "Coordinator runtime started on 0.0.0.0:8765",
    severity: "info",
  },
  {
    id: "log-015",
    timestamp: "2026-02-01T10:00:00Z",
    action: "agent.revoked",
    actor: "admin@corp.example",
    target: "agent-slack-bot",
    target_type: "agent",
    details: "Revoked: agent exhibited unexpected behaviour in production",
    severity: "critical",
  },
];

// ── Dashboard Stats ───────────────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  total_agents: 12,
  approved_agents: 5,
  pending_agents: 1,
  managed_agents: 3,
  ephemeral_agents: 3,
  active_sessions: 1,
  total_sessions_today: 3,
  llm_provider: "openai",
  llm_model: "gpt-4o",
};
